name: Pipeline CI

on:
  push:
    # CORRECCIÓN: Cambiado de "main" a "master" para coincidir con tu rama actual
    branches: [ "master" ]

jobs:
  probar-y-subir:
    runs-on: ubuntu-latest
    steps:
    - name: Bajar código
      uses: actions/checkout@v3
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Ejecutar Tests
      # Ejecutará tus pruebas unitarias en PRODUCTOS.Tests.Unit
      run: dotnet test 

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Construir y Subir Imagen de Productos
      uses: docker/build-push-action@v4
      with:
        # El contexto es la raíz para ver todos los proyectos de la solucion ..
        context: .
        # Ruta validada en tu Explorador de Soluciones
        file: ./PRODUCTOS.API/Dockerfile 
        push: true
        # Se usará euler09/productos-api:latest
        tags: ${{ secrets.DOCKER_USERNAME }}/productos-api:latest