name: Pipeline CI

on:
  push:
    branches: [ "main" ]

jobs:
  probar-y-subir:
    runs-on: ubuntu-latest
    steps:
    - name: Bajar código
      uses: actions/checkout@v3
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Ejecutar Tests
      # Busca automáticamente los proyectos de prueba como PRODUCTOS.Tests.Unit
      run: dotnet test 

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Construir y Subir Imagen de Productos
      uses: docker/build-push-action@v4
      with:
        # El contexto debe ser la raíz (.) para que Docker pueda copiar todas las capas del microservicio
        context: .
        # RUTA SEGÚN TU EXPLORADOR: Se encuentra dentro de la carpeta PRODUCTOS.API
        file: ./PRODUCTOS.API/Dockerfile 
        push: true
        # Se etiqueta con tu usuario (euler09) y el nombre del repo
        tags: ${{ secrets.DOCKER_USERNAME }}/productos-api:latest